### ISSUE TITLE
Elite C Problems

### ISSUE THREAD

**Issue by ltv0** [CrazyRedMachine/LUFAHybridFightstick#10]
I assumed since the Elite C was based on a pro micro that it would work with this firmware. Everytime I try to use it, the bumpers and triggers don't work. 

using the pcb from [this project](https://github.com/jfedor2/flatbox)

**Comment by CrazyRedMachine** [comment]
hi, it's probably just a pin mapping issue, if it's based on pro micro it can probably work.. don't forget to disable with_analog mode if you don't have real analog sticks on your controller

**Comment by ltv0** [comment]
It has a DFU bootloader so I had to turn the files into a .hex. I accidentally left define analog on and it made the buttons I was gonna map act as the left and right sticks. Now they won't appear at all when I test it. The 4 buttons on the right side of the controller are where i was gonna use the bumpers&triggers.

[Heres my code at the moment](https://drive.google.com/drive/folders/1SnfHOg-xHhJAjg7Z7shYbCSxbDhzO0Ye?usp=sharing) and [here is the pin out for the pcb I am using at the moment.](https://github.com/jfedor2/flatbox/blob/master/hardware-rev1/extras/Flatbox-rev1-schematic.pdf)

**Comment by CrazyRedMachine** [comment]
i cannot download from that google drive

based on the pcb pinout yes the code will be compatible as long as you comment out (or just delete) the #define WITH_ANALOG on line 14, and set your pin mapping (the only place where you should change pinout is there and next lines : https://github.com/CrazyRedMachine/LUFAHybridFightstick/blob/4497b245b819b18700de2b84728811332de14d04/LUFAHybridFightstick/LUFAHybridFightstick.ino#L27 

Note that you should use the arduino pin names (same as what is written on the pro micro silkscreen)

**Comment by ltv0** [comment]
[https://youtu.be/rKOMj--7vgM](url)

I changed the pinout and it doesn't seem to work. I set the L1,l2,r1,r2 to what the analog values were and it still doesn't work. I think its probably because the elite c uses a dfu bootloader.

**Comment by CrazyRedMachine** [comment]
code looks ok so I'd check the wiring. Make sure all buttons have a common ground which is wired to gnd, and that each button goes to the corresponding pin (if you have another pro micro lying around you can also try it, without wiring anything to it and just using a simple wire to short GND and each pin). 
bootloader shouldn't change what happens once the sketch is running, it just changes what happens before that.

**Comment by ltv0** [comment]
oh the original raw pin on the elite c is replaced with something else. thats probably the reason.

**Comment by CrazyRedMachine** [comment]
doesn't sound like it would matter, sounds more like something is different either with the analog pins or with the way the trigger buttons are wired to the pcb.
