### ISSUE TITLE
Pins for joysticks

### ISSUE THREAD

**Issue by D4vv1-1d** [CrazyRedMachine/LUFAHybridFightstick#13]
which are these pins for one joystick or for 2? If it is for 2 which is for left and right?  
#ifdef WITH_ANALOG
#define PIN_LANALOGX    A0
#define PIN_LANALOGY    A1
#define PIN_RANALOGX    A2
#define PIN_RANALOGY    A3

**Comment by CrazyRedMachine** [comment]
LANALOGX = left analog X axis
LANALOGY = left analog Y axis
RANALOGX = right analog X axis
RANALOGY = right analog Y axis

**Comment by D4vv1-1d** [comment]
Sorry I didn’t read it properly but thankyou
