### ISSUE TITLE
Error compiling for board Arduino Leonardo (LUFA).

### ISSUE THREAD

**Issue by D4vv1-1d** [CrazyRedMachine/LUFAHybridFightstick#14]
Hi, I have an error saying  Error compiling for board Arduino Leonardo (LUFA) and I don't  understand what is wrong because I am shaw I followed the orders

**Comment by CrazyRedMachine** [comment]
you should enable verbose output during compilation and flash in the arduino ide preferences.
then you check what errors you have in the bottom frame. "compilation error" by itself gives no useful info for anyone to help you..

make sure you installed the Bounce2 lib as well. Also try to compile the code as is at least once before adding your changes to verify your install is ok

**Comment by D4vv1-1d** [comment]
ok i will try that

**Comment by D4vv1-1d** [comment]
this is the fool error 

Multiple libraries were found for "Descriptors.h"
 Used: C:\Users\OneDrive\Documents\Arduino\libraries\LUFAHybridFightstick
In file included from C:\Users\AppData\Local\Temp\arduino_modified_sketch_590784\LUFAHybridFightstick.ino:1:0:
 Not used: C:\Users\OneDrive\Documents\Arduino\libraries\LUFAHYBRIDLibary
C:\Users\OneDrive\Documents\Arduino\libraries\LUFAHybridFightstick/Descriptors.h:7:10: fatal error: LUFA/LUFA/Drivers/USB/USB.h: No such file or directory
 Not used: C:\Users\OneDrive\Documents\Arduino\libraries\ATMega32U4-Switch-Fightstick-master
 #include <LUFA/LUFA/Drivers/USB/USB.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Leonardo (LUFA).

**Comment by CrazyRedMachine** [comment]
LUFAHybridFightstick is not a library it's just a regular sketch, you shouldn't be extracting these in your library folder... also looks like you didn't install the lufa boards correctly (i recommend using my repo link to install them via the board manager).

basically download the zip from this repo, extract somewhere (e.g  c:\lufahybrid\) open the .ino file, select lufa board and flash from there...

**Comment by D4vv1-1d** [comment]
I used the URL
for the lufa board

**Comment by D4vv1-1d** [comment]
it works now thanks

**Comment by D4vv1-1d** [comment]
Because there is no joystick.h
