### ISSUE TITLE
How do I make LEFT+RIGHT = Last Input as default?

### ISSUE THREAD

**Issue by ShazK04** [CrazyRedMachine/LUFAHybridFightstick#18]
My custom controller doesn't have L3 and R3 so I can't switch SOCD configs, but I want it to have UP+DOWN = UP, and LEFT+RIGHT = Last Input. How do I make that the default?

**Comment by CrazyRedMachine** [comment]
you change lines 107 108 to change the default values, and you keep socd_config set to off since you don't have l3/r3
