### ISSUE TITLE
How to use only digital input / directional inputs

### ISSUE THREAD

**Issue by RryaAnqr4prWxD2kFCFm** [CrazyRedMachine/LUFAHybridFightstick#21]
Im trying to figure out if its possible to map each dpad button to a separate pin. I can only find the up button.

**Comment by CrazyRedMachine** [comment]
i don't understand the question. of course there are pins for up/down/left/right else the dpad wouldn't work.. check the pin definitions on top of the .ino file

**Comment by RryaAnqr4prWxD2kFCFm** [comment]
#define PIN_UP    MOSI
#define PIN_DOWN  1
#define PIN_LEFT  SS
#define PIN_RIGHT 0

These ones right? I'm using pro micro and I do not have these pins there? If I were to reassign them to other pins will the code work?
