### ISSUE TITLE
PS Support Question

### ISSUE THREAD

**Issue by wanildopneto** [CrazyRedMachine/LUFAHybridFightstick#6]
Hello,
Would it be possible to add PS4/PS5 support by using the same method that made the Switch mode work?
IE, all the device descriptor stuff plus adding Direct Input support?

**Comment by CrazyRedMachine** [comment]
Hi,
unfortunately not, PS4/5 works differently (controller has a private key which is used to authenticate during the pairing process, and it would be illegal to publish firmware code containing such data).
This is why a lot of commercial ps4 adapters require a real controller to plug on the adapter to perform auth passthrough.
