### ISSUE TITLE
Dpad

### ISSUE THREAD

**Issue by minkuluk** [CrazyRedMachine/LUFAHybridFightstick#8]
how to set it as Dpad mode only ?

**Comment by CrazyRedMachine** [comment]
you can use the key combo to switch to dpad mode as explained in the readme.
if you mean forcing dpad only and deactivating the other modes, then you can force state to DIGITAL in the code and disable the checkmodechange calls.

**Comment by minkuluk** [comment]
thanks man, keep up the good work.. God Bless You.
